---
title: "Match promedios de notas"
---

```{r}
#| echo: false

pacman::p_load(knitr, digest, stargazer, sjPlot, codebook, summarytools, dplyr, tidyr,
 tidyLPA, lme4, ggplot2, ggeffects, skimr, table1, patchwork, here, kableExtra, ggthemes, tidyverse,
 ggbreak, texreg, coefplot)

options(scipen = 999)
```
```{r}
#| echo: false


base_madre <- readRDS("../../../../input/data/proc_data/base_madre.rds")
socio <- readRDS("../../../../input/data/proc_data/df_socio.rds")
psico <- readRDS("../../../../input/data/proc_data/df_psico.rds")
trabajo <- readRDS("../../../../input/data/proc_data/df_trabajo.rds")
educa <- readRDS("../../../../input/data/proc_data/df_parvularia.rds")
antropo <- readRDS("../../../../input/data/proc_data/df_antropo.rds")
```

```{r}
#| echo: false

base_madre <- base_madre %>%
  filter(cohorte %in% c(2021, 2022, 2023, 2024))
```

```{r}
#| echo: false
#| warning: false
#| label: fig-facso-full
#| fig-cap: Asociación entre Promedio por defecto y Promedio calculado - FACSO
#| fig-cap-location: top

r_facso <- cor(x = base_madre$promedio_ucampus, 
    y = base_madre$promedio_calculado, 
    use = "complete.obs")

sjPlot::plot_scatter(
  data = base_madre, 
  x = promedio_ucampus,
  y = promedio_calculado
) +
  geom_label(
    aes(
      x = Inf, y = -Inf,
      label = paste0("r = ", round(r_facso, 2))
    ),
    hjust = 1.1,
    vjust = -0.2,
    size = 5,
    color = "black",
    fill = "white",      # color del recuadro
    line.width = 0.3     # grosor del borde
  )
```

```{r}
#| echo: false
#| warning: false
#| label: fig-socio-full
#| fig-cap: Asociación entre Promedio bruto y Promedio calculado - Sociología
#| fig-cap-location: top

r_socio <- cor(x = socio$promedio_ucampus, 
    y = socio$promedio_calculado, 
    use = "complete.obs")

sjPlot::plot_scatter(
  data = socio, 
  x = promedio_ucampus,
  y = promedio_calculado
) +
  geom_label(
    aes(
      x = Inf, y = -Inf,
      label = paste0("r = ", round(r_socio, 2))
    ),
    hjust = 1.1,
    vjust = -0.2,
    size = 5,
    color = "black",
    fill = "white",      # color del recuadro
    line.width = 0.3     # grosor del borde
  )
```

```{r}
#| echo: false
#| warning: false
#| label: fig-psico-full
#| fig-cap: Asociación entre Promedio bruto y Promedio calculado - Psicología
#| fig-cap-location: top

r_psico <- cor(x = psico$promedio_ucampus, 
    y = psico$promedio_calculado, 
    use = "complete.obs")

sjPlot::plot_scatter(
  data = psico, 
  x = promedio_ucampus,
  y = promedio_calculado
) +
  geom_label(
    aes(
      x = Inf, y = -Inf,
      label = paste0("r = ", round(r_psico, 2))
    ),
    hjust = 1.1,
    vjust = -0.2,
    size = 5,
    color = "black",
    fill = "white",      # color del recuadro
    line.width = 0.3     # grosor del borde
  )
```

```{r}
#| echo: false
#| warning: false
#| label: fig-trabajo-full
#| fig-cap: Asociación entre Promedio bruto y Promedio calculado - Trabajo social
#| fig-cap-location: top

r_trabajo <- cor(x = trabajo$promedio_ucampus, 
    y = trabajo$promedio_calculado, 
    use = "complete.obs")

sjPlot::plot_scatter(
  data = trabajo, 
  x = promedio_ucampus,
  y = promedio_calculado
) +
  geom_label(
    aes(
      x = Inf, y = -Inf,
      label = paste0("r = ", round(r_trabajo, 2))
    ),
    hjust = 1.1,
    vjust = -0.2,
    size = 5,
    color = "black",
    fill = "white",      # color del recuadro
    line.width = 0.3     # grosor del borde
  )
```

```{r}
#| echo: false
#| warning: false
#| label: fig-educa-full
#| fig-cap: Asociación entre Promedio bruto y Promedio calculado - Educación Parvularia
#| fig-cap-location: top

r_educa <- cor(x = educa$promedio_ucampus, 
    y = educa$promedio_calculado, 
    use = "complete.obs")

sjPlot::plot_scatter(
  data = educa, 
  x = promedio_ucampus,
  y = promedio_calculado
) +
  geom_label(
    aes(
      x = Inf, y = -Inf,
      label = paste0("r = ", round(r_educa, 2))
    ),
    hjust = 1.1,
    vjust = -0.2,
    size = 5,
    color = "black",
    fill = "white",      # color del recuadro
    line.width = 0.3     # grosor del borde
  )
```

```{r}
#| echo: false
#| warning: false
#| label: fig-antropo-full
#| fig-cap: Asociación entre Promedio bruto y Promedio calculado - Antropología Arqueología
#| fig-cap-location: top

r_antropo <- cor(x = antropo$promedio_ucampus, 
    y = antropo$promedio_calculado, 
    use = "complete.obs")

sjPlot::plot_scatter(
  data = antropo, 
  x = promedio_ucampus,
  y = promedio_calculado
) +
  geom_label(
    aes(
      x = Inf, y = -Inf,
      label = paste0("r = ", round(r_antropo, 2))
    ),
    hjust = 1.1,
    vjust = -0.2,
    size = 5,
    color = "black",
    fill = "white",      # color del recuadro
    line.width = 0.3     # grosor del borde
  )
```